apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
    - ../../../base/

resources:
    - pv.yml
    - pvc.yml

namespace: plex

patchesStrategicMerge:
    - dep.yml
    - svc_tcp.yml
    - svc_udp.yml
    - ns.yml

commonLabels:
    app: plex

configMapGenerator:
    - name: plex-env-vars
      behavior: replace
      literals:
        - TZ=America/Los_Angeles
        - PLEX_UID=1002
        - PLEX_GID=1007
        - ADVERTISE_IP=http://192.168.50.155:32400
        - HOSTNAME=janus.sol.milkyway
        - ALLOWED_NETWORKS=0.0.0.0/0
        - PLEX_CLAIM="CLAIMTOKEN"
