apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
    - ../../base/

resources:
    - pv.yml
    - pvc.yml
    # - vs.yml
    # - gw.yml

namespace: tautulli

patchesStrategicMerge:
    - ns.yml
    - dep.yml
    - svc.yml

commonLabels:
    app: tautulli

configMapGenerator:
    - name: tautulli-env-vars
      literals:
        - TZ='America/Los_Angeles'
        - PUID='1002'
        - PGID='1007'
