apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: federated-monitoring

resources:
    - Prometheus
    # - cAdvisor
    # - Kube_State_Metrics
    # - Node_Exporter

commonLabels:
    app: federated_monitoring
