# https://www.talos.dev/v1.5/kubernetes-guides/configuration/deploy-metrics-server/
resources:
  - resources/namespace.yml # https://github.com/argoproj/argo-cd/issues/11625#issuecomment-1741915734

helmCharts:
  - name: metrics-server
    repo: https://kubernetes-sigs.github.io/metrics-server/
    version: 3.12.2 # https://artifacthub.io/packages/helm/metrics-server/metrics-server?modal=changelog
    releaseName: metrics-server
    namespace: metrics-server
    valuesFile: values.yml
    includeCRDs: true
