namespace: radarr-system

resources:
  - resources/namespace.yml
  - resources/persistentVolume.yml
  - resources/persistentVolumeClaim.yml
  - resources/service.yml
  - resources/statefulset.yml

commonLabels:
  app.kubernetes.io/name: radarr

images:
  - name: linuxserver/radarr
    newTag: 5.2.6 # https://hub.docker.com/r/linuxserver/radarr/tags

configMapGenerator:
  - name: radarr-env-vars
    literals:
      - TZ="America/Los_Angeles"
      - PUID="65534"
      - PGID="65534"
