apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - ../../base/

resources:
  - pv.yml
  - pvc.yml

patchesStrategicMerge:
  - dep.yml
  - dep_postgres.yml
  - svc.yml
  - ns.yml

namespace: jira

configMapGenerator:
  - name: jira-env-vars
    literals:
      - ATL_DB_TYPE="postgres72"
      - ATL_DB_DRIVER="org.postgresql.Driver"
      - ATL_JDBC_URL="jdbc:postgresql://postgres:5432/jira"
      - ATL_JDBC_USER="jira"
      - JVM_MAXIMUM_MEMORY="4096m"
      - JVM_MINIMUM_MEMORY="1024m"
      - POSTGRES_USER="jira"

secretGenerator:
  - name: jira-postgres-password
    envs:
      - jira_postgres_password
