resources:
  - https://raw.githubusercontent.com/alex1989hu/kubelet-serving-cert-approver/main/deploy/standalone-install.yaml
  - https://github.com/kubernetes-sigs/metrics-server/releases/latest/download/components.yaml
