helmCharts:
  - name: argo-workflows
    repo: https://argoproj.github.io/argo-helm
    version: 0.40.9 # https://artifacthub.io/packages/helm/argo/argo-workflows?modal=changelog
    releaseName: argo-workflows
    namespace: argo-system
    valuesFile: values.yml
    includeCRDs: true
