apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
    - ../../base/

resources:
    - pv.yml
    - pvc.yml

patchesStrategicMerge:
    - dep.yml
    - svc_tcp.yml
    - svc_udp.yml

namespace: openvpn

commonLabels:
    app: openvpn

configMapGenerator:
    - name: openvpn-env-vars
      literals:
        - TZ='America/Los_Angeles'
        - PUID='1002'
        - PGID='1007'
